General:
  AutoCreateAccounts: true
  SignMessage: Premium
  Points: Points
  Transferrable: true
  ExpireOnStartup: true
  AutoFillSigns: true
  SpecificPermissions: false
  PurgeEmptyAccountsOnStartup: true
  ServerName: Minecraft Server
  ExpirationCheckTimer: 300
MySQL:
  engine: sqlite
  SQLiteDB: donationpoints.db
  host: localhost
  port: 3306
  username: root
  password: ''
  database: minecraft
  TransactionTable: dp_transactions
  PlayerTable: dp_players
  ItemFrameTable: dp_frames
messages:
  Prefix: '&7[&aDonationPoints&7]'
  RestrictedWorld: '&cYou cannot purchase that in this world.  You need to be in : %worlds'
  NoPermission: '&cYou dont have permission to do that.'
  InvalidArguments: '&cYou have specified an incorrect number of arguments.'
  PlayerOnly: '&cThis command is only available to players.'
  ReloadSuccessful: '&cConfig file has been successfully reloaded.'
  NoCommandExists: '&cThat is not a valid DonationPoints command.'
  DPConfirm: '&cType &3/dp confirm &cto confirm your purchase of &3%pack &cfor &3%amount points&c.'
  DPActivate: '&cType &3/dp activate %pack &cto activate your purchase.'
  DPSuccessfulActivation: '&cYou have activated your &3%pack &cpackage.'
  DPFailedActivation: '&cYou do not have a &3%pack &cto activate.'
  ExpireDate: '&cYour &3%pack &cis set to expire on &3%expiredate&c.'
  DPGive: '&3%amount &chas been added to &3%player &cbalance'
  DPTake: '&3%amount &chas been removed from &%3players &c balance.'
  DPSet: '&3%player &caccount has been set to &3%amount points&c.'
  NoAccount: '&cNo account found for &3%player&c.'
  AccountCreated: '&cAn account has been created for &3%player&c.'
  AccountAlreadyExists: '&cAn account already exists for &3player&c.'
  NoTransfer: '&cUnable to make the transfer.'
  TransferOff: '&cThis server does not have transfers enabled.'
  TransferSent: '&cYou have sent &3%amount &cto &3%player&c.'
  TransferReceive: '&cYou have received &3%amount &cfrom &3%player.'
  PlayerBalance: '&cYou have a balance of &3%amount&c.'
  OtherBalance: '&3%player &chas a balance of &3%amount&c.'
  NoPurchaseStarted: '&cYou have not yet started a purchase.'
  PurchaseSuccessful: '&cYou have purchased &3%pack &cfor &3%amount points&c.'
  NeedActivation: '&cYou have already purchased &3%pack &cbut it is not active.'
  TooLongOnConfirm: '&cYou waited too long to confirm your purchase. Purchase canceled.'
  LimitReached: '&cYou have already reached the limit of &3%limit &cpurchases of &3%pack&c.'
  PackageActivated: '&cYou have successfully activated your &3%pack &cpackage'
  InvalidPackage: '&cUnable to find that package.'
  NotEnoughPoints: '&cYou dont have enough points to make that purchase.'
  DPPrerequisite: '&cYou must purchase &3%pack &cbefore you can purchase this one.'
  SignLeftClick: '&cRight click to purchase &3%pack &cfor &3%price points&c.'
  SignLeftClickDescription: '&7[&cDescription&7] &a%desc'
  RequiredInventorySpace: '&cYou need at least &3%slot &cinventory slots to purchase this package.'
